# Generated by Django 6.0 on 2025-12-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_peminjam', models.CharField(max_length=100)),
                ('judul_buku', models.CharField(max_length=150)),
                ('pengarang', models.CharField(max_length=100)),
                ('tanggal_pinjam', models.DateField()),
                ('tanggal_kembali', models.DateField()),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], default='Dipinjam', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Data Peminjaman',
            },
        ),
    ]
